bind_addr = ":8080"
log_lovel = "error"
database_url = "host=localhost dbname=s3 sslmode=disable user=postgres password=postgres"
store_path = "storage"
secret_key = "secretKey"
api_gateway_url = "http://127.0.0.1:7000"